BEGIN;
ALTER TABLE pengambilan_mata_kuliah DROP CONSTRAINT IF EXISTS pengambilan_mata_kuliah_nilai_huruf_check;
UPDATE pengambilan_mata_kuliah SET nilai_huruf = CASE nilai_huruf WHEN 'A-' THEN 'A' WHEN 'B-' THEN 'B' WHEN 'C-' THEN 'C' ELSE nilai_huruf END WHERE nilai_huruf IN ('A-','B-','C-');
ALTER TABLE pengambilan_mata_kuliah ADD CONSTRAINT pengambilan_mata_kuliah_nilai_huruf_check CHECK (nilai_huruf IS NULL OR nilai_huruf IN ('A','B+','B','C+','C','D','E'));
DROP VIEW v_ringkasan_akademik;
DROP VIEW v_nilai_efektif;
CREATE VIEW v_nilai_efektif AS SELECT ranked.*,ranked.nilai_huruf IN ('A','B+','B','C+','C','D') AS lulus,ranked.nilai_huruf IN ('D','E') AS perlu_perhatian FROM (SELECT p.id AS pengambilan_id,p.mahasiswa_user_id,p.mata_kuliah_id,mk.kode AS kode_mata_kuliah,mk.nama AS nama_mata_kuliah,mk.sks,p.periode_akademik_id,pa.kode AS kode_periode,p.attempt,p.nilai_angka,p.nilai_huruf,COALESCE(p.bobot_nilai,CASE p.nilai_huruf WHEN 'A' THEN 4 WHEN 'B+' THEN 3.5 WHEN 'B' THEN 3 WHEN 'C+' THEN 2.5 WHEN 'C' THEN 2 WHEN 'D' THEN 1 WHEN 'E' THEN 0 END)::NUMERIC(3,2) AS bobot_efektif,p.source_document_id,p.academic_import_id,ROW_NUMBER() OVER (PARTITION BY p.mahasiswa_user_id,p.mata_kuliah_id ORDER BY COALESCE(p.bobot_nilai,CASE p.nilai_huruf WHEN 'A' THEN 4 WHEN 'B+' THEN 3.5 WHEN 'B' THEN 3 WHEN 'C+' THEN 2.5 WHEN 'C' THEN 2 WHEN 'D' THEN 1 WHEN 'E' THEN 0 END) DESC,p.nilai_angka DESC NULLS LAST,pa.tanggal_selesai DESC,p.attempt DESC,p.id DESC) AS nilai_rank FROM pengambilan_mata_kuliah p JOIN mata_kuliah mk ON mk.id=p.mata_kuliah_id JOIN periode_akademik pa ON pa.id=p.periode_akademik_id WHERE p.status='selesai' AND p.nilai_huruf IS NOT NULL) ranked WHERE nilai_rank=1;
CREATE VIEW v_ringkasan_akademik AS SELECT mahasiswa_user_id,COUNT(*) AS total_mata_kuliah_dinilai,COUNT(*) FILTER (WHERE nilai_huruf='A') AS jumlah_a,COUNT(*) FILTER (WHERE nilai_huruf IN ('B+','B')) AS jumlah_b,COUNT(*) FILTER (WHERE nilai_huruf IN ('C+','C')) AS jumlah_c,COUNT(*) FILTER (WHERE nilai_huruf='D') AS jumlah_d,COUNT(*) FILTER (WHERE nilai_huruf='E') AS jumlah_e,COUNT(*) FILTER (WHERE perlu_perhatian) AS jumlah_d_e,COUNT(*) FILTER (WHERE nilai_huruf='E') AS jumlah_wajib_diulang,GREATEST(COUNT(*) FILTER (WHERE nilai_huruf='D')-3,0) AS jumlah_d_melebihi_batas,COALESCE(SUM(sks) FILTER (WHERE lulus),0) AS sks_lulus,COALESCE(SUM(sks) FILTER (WHERE perlu_perhatian),0) AS sks_d_e,ROUND(SUM(bobot_efektif*sks)/NULLIF(SUM(sks),0),2) AS ipk_efektif FROM v_nilai_efektif GROUP BY mahasiswa_user_id;
COMMIT;
