const db = require('../config/db');
const repository = require('../repositories/academic.repository');
const gradePoints = { A: 4, 'B+': 3.5, B: 3, 'C+': 2.5, C: 2, D: 1, E: 0 };
const asObject = (value) => { if (value && typeof value === 'object') return value; try { return JSON.parse(String(value).trim().replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '')); } catch (_) { return null; } };
const ensureMahasiswa = (user) => { if (!user || user.role !== 'mahasiswa') throw { status: 403, message: 'Hanya mahasiswa yang dapat mengakses data akademik personal' }; };
exports.getSummary = ({ user }) => { ensureMahasiswa(user); return repository.getSummary(user.id); };
exports.getCourses = ({ user }) => { ensureMahasiswa(user); return repository.getEffectiveCourses(user.id); };
exports.getRecommendations = ({ user }) => { ensureMahasiswa(user); return repository.getRecommendations(user.id); };
exports.importKhs = async ({ documentId, payload }) => {
  const parsed = asObject(payload); if (!parsed) throw { status: 422, message: 'Hasil ekstraksi KHS bukan JSON yang valid' };
  const document = await repository.findDocument(documentId); if (!document || document.document_type !== 'khs') throw { status: 422, message: 'Dokumen sumber bukan KHS yang valid' };
  const curriculum = await repository.findStudentCurriculum(document.user_id); if (!curriculum) throw { status: 422, message: 'Kurikulum mahasiswa belum ditetapkan' };
  const items = parsed.daftar_nilai || parsed.data?.daftar_nilai || parsed.items || []; if (!Array.isArray(items) || !items.length) throw { status: 422, message: 'Hasil ekstraksi KHS tidak memiliki daftar nilai' };
  const info = parsed.informasi_semester || parsed.semester_info || {}; const match = String(info.tahun_ajaran || '').match(/(19|20)\d{2}/); const year = match ? Number(match[0]) : new Date().getFullYear(); const kind = /genap|even/i.test(String(info.tahun_ajaran || '')) ? 'genap' : 'ganjil';
  const rows = items.map((item) => { const code = String(item.kode_mk || item.kode || item.kode_matakuliah || '').trim().toUpperCase(); const name = String(item.nama_mk || item.nama || item.nama_mata_kuliah || '').trim(); const grade = String(item.huruf_mutu || item.nilai_huruf || item.nilai || '').trim().toUpperCase(); const score = Number(String(item.nilai_angka || item.nilai_numerik || '').replace(',', '.')); if (!code || !name || !Object.hasOwn(gradePoints, grade)) throw { status: 422, message: 'Item KHS memiliki kode, nama, atau nilai yang tidak valid' }; return { code, name, grade, score: Number.isFinite(score) && score >= 0 && score <= 100 ? score : null, raw: item }; });
  const client = await db.connect(); try { await client.query('BEGIN'); const periodId = await repository.findOrCreatePeriod(client, { tahunMulai: year, jenisSemester: kind }); const importId = await repository.createImport(client, { mahasiswaUserId: document.user_id, documentId: document.id, periodId, curriculumId: curriculum.id, type: 'khs', key: `khs:${document.id}:${document.uploaded_at}`, raw: parsed }); await repository.replaceImportedRows(client, { documentId: document.id, mahasiswaUserId: document.user_id }); for (const item of rows) { const course = await repository.findCourseForCurriculum(curriculum.id, item.code, item.name); if (!course) throw { status: 422, message: `Mata kuliah ${item.code} tidak ditemukan di master kurikulum` }; await repository.insertCourseResult(client, { mahasiswaUserId: document.user_id, courseId: course.id, periodId, importId, documentId: document.id, score: item.score, grade: item.grade, point: gradePoints[item.grade], raw: item.raw }); } await repository.finishImport(client, importId); await client.query('COMMIT'); return { import_id: importId, document_id: document.id, imported_items: rows.length }; } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); }
};
exports.importCurriculum = async ({ knowledgeBaseId, payload }) => { const parsed = asObject(payload) || payload; const courses = parsed?.courses || parsed?.mata_kuliah || []; if (!Number.isInteger(Number(parsed?.kurikulum_id)) || !Array.isArray(courses) || !courses.length) throw { status: 422, message: 'Callback kurikulum membutuhkan kurikulum_id dan courses' }; const client = await db.connect(); try { await client.query('BEGIN'); const importId = await repository.createImport(client, { knowledgeBaseId, type: 'kurikulum', key: `kurikulum:${knowledgeBaseId}:${parsed.version || 'current'}`, raw: parsed }); for (const item of courses) { const code = String(item.kode || item.kode_mk || '').trim().toUpperCase(); const name = String(item.nama || item.nama_mk || '').trim(); const sks = Number(item.sks || item.kredit); if (!code || !name || !Number.isInteger(sks) || sks < 1 || sks > 12) throw { status: 422, message: `Data mata kuliah kurikulum tidak valid: ${code || 'kode kosong'}` }; const courseId = await repository.upsertCourse(client, { code, name, sks }); await repository.upsertCurriculumCourse(client, { curriculumId: Number(parsed.kurikulum_id), courseId, semester: Number(item.semester) || null, sifat: item.sifat === 'pilihan' ? 'pilihan' : 'wajib' }); } await repository.finishImport(client, importId); await client.query('COMMIT'); return { import_id: importId, knowledge_base_id: knowledgeBaseId, imported_items: courses.length }; } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } };
