steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - asia-southeast2-docker.pkg.dev/$PROJECT_ID/backend/acaris-docs:$SHORT_SHA
      - services/docs-service

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia-southeast2-docker.pkg.dev/$PROJECT_ID/backend/acaris-docs:$SHORT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - acaris-docs
      - --image
      - asia-southeast2-docker.pkg.dev/$PROJECT_ID/backend/acaris-docs:$SHORT_SHA
      - --region
      - asia-southeast2
      - --platform
      - managed
      - --allow-unauthenticated
      - --port
      - "8080"
      - --set-env-vars
      - ACARIS_API_BASE_URL=https://acaris.my.id/api,ACARIS_ALLOWED_API_BASES=https://acaris.my.id/api

images:
  - asia-southeast2-docker.pkg.dev/$PROJECT_ID/backend/acaris-docs:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
